/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health and the loaded project */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load the GUI bootstrap context */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the loaded project */
        get: operations["getProject"];
        /** Replace editable project metadata */
        put: operations["updateProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project environments */
        get: operations["listEnvironments"];
        put?: never;
        /** Create an environment */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        /** Get an environment */
        get: operations["getEnvironment"];
        /** Replace an environment without changing its ID */
        put: operations["updateEnvironment"];
        post?: never;
        /** Delete an environment */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in configuration packs */
        get: operations["listPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/{pack_name}/versions/{pack_version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        /** Get a versioned configuration pack metadata */
        get: operations["getPack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/{pack_name}/versions/{pack_version}/schema": {
        parameters: {
            query?: {
                /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
                schema_version?: components["parameters"]["SchemaVersion"];
            };
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        /** Get a configuration pack form schema */
        get: operations["getPackSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            project_id: string;
        };
        BootstrapResponse: {
            data: components["schemas"]["BootstrapData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        BootstrapData: {
            project: components["schemas"]["Project"];
            environments: components["schemas"]["Environment"][];
            capabilities: components["schemas"]["Capabilities"];
        };
        ManifestState: {
            project: components["schemas"]["Project"];
            environments: components["schemas"]["Environment"][];
        };
        ProjectResponse: {
            data: components["schemas"]["Project"];
            meta: components["schemas"]["ResponseMeta"];
        };
        EnvironmentsResponse: {
            data: components["schemas"]["Environment"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        EnvironmentResponse: {
            data: components["schemas"]["Environment"];
            meta: components["schemas"]["ResponseMeta"];
        };
        DeleteEnvironmentResponse: {
            data: {
                deleted_id: string;
            };
            meta: components["schemas"]["ResponseMeta"];
        };
        PackListResponse: {
            data: components["schemas"]["PackSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        PackMetadataResponse: {
            data: components["schemas"]["PackMetadata"];
            meta: components["schemas"]["ResponseMeta"];
        };
        PackSchemaResponse: {
            data: components["schemas"]["PackSchema"];
            meta: components["schemas"]["ResponseMeta"];
        };
        ResponseMeta: {
            request_id: string;
            revision: number;
        };
        Project: {
            id: string;
            name: string;
            pack_ref: string;
            /** @enum {string} */
            source_type: "managed-file" | "git-json";
        };
        UpdateProjectInput: {
            id: string;
            name: string;
        };
        /**
         * @example {
         *       "id": "production",
         *       "name": "Production",
         *       "kind": "production",
         *       "provider": {
         *         "type": "firebase-remote-config",
         *         "project_id": "photo-editor-prod"
         *       },
         *       "publish": {
         *         "requires_confirmation": true
         *       }
         *     }
         */
        Environment: {
            /** @description Stable opaque environment identifier. It cannot be changed after creation and carries no environment semantics. */
            id: string;
            /** @description Human-readable environment name shown in the UI. */
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        CreateEnvironmentInput: {
            id: string;
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        UpdateEnvironmentInput: {
            name: string;
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        /**
         * @description Server-authoritative environment category. Only production activates the persistent Production UI state. It cannot be changed after creation.
         * @enum {string}
         */
        EnvironmentKind: "development" | "staging" | "production" | "custom";
        ProviderConfig: {
            /** @constant */
            type: "firebase-remote-config";
            project_id: string;
        };
        PublishConfig: {
            requires_confirmation: boolean;
        };
        Capabilities: {
            /** @constant */
            project_edit: true;
            /** @constant */
            environment_manage: true;
        };
        PackSummary: {
            ref: string;
            name: string;
            version: string;
            description: string;
        };
        PackMetadata: {
            ref: string;
            name: string;
            version: string;
            description: string;
            capabilities: string[];
            schema_version: number;
            entity_types: components["schemas"]["EntityMetadata"][];
        };
        EntityMetadata: {
            name: string;
            label: string;
            description: string;
            id_rule: components["schemas"]["IDRule"];
            /** @enum {string} */
            deletion_policy: "restrict" | "cascade" | "allow";
            environment_override_fields: string[];
        };
        IDRule: {
            pattern: string;
            min_length: number;
            max_length: number;
        };
        PackSchema: {
            version: number;
            entities: components["schemas"]["EntitySchema"][];
            migrations: components["schemas"]["SchemaMigration"][];
        };
        EntitySchema: {
            name: string;
            fields: components["schemas"]["FieldSchema"][];
        };
        FieldSchema: {
            name: string;
            /** @enum {string} */
            type: "string" | "boolean" | "integer" | "number" | "object" | "array" | "reference";
            required: boolean;
            default: unknown;
            /** @enum {string} */
            sensitivity: "public" | "sensitive";
            ui: components["schemas"]["FieldUI"];
            validation: components["schemas"]["FieldValidation"];
        };
        FieldUI: {
            label: string;
            description: string;
            control: string;
            group: string;
            order: number;
            placeholder?: string;
        };
        FieldValidation: {
            enum: unknown[];
            min_length?: number;
            max_length?: number;
            minimum?: number;
            maximum?: number;
        };
        SchemaMigration: {
            from_version: number;
            to_version: number;
            description: string;
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
        ManifestRevisionMismatchResponse: {
            error: components["schemas"]["ManifestRevisionMismatchError"];
        };
        ManifestRevisionMismatchError: {
            /** @constant */
            code: "revision_mismatch";
            message: string;
            request_id: string;
            /** @description Revision of current_state and the ETag response header. */
            current_revision: number;
            current_state: components["schemas"]["ManifestState"];
        };
        Error: {
            code: string;
            message: string;
            request_id: string;
            current_revision?: number;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            path?: string;
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description Malformed JSON, unknown fields, or invalid request headers. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Browser origin is not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists or the current state forbids the operation. */
        StateConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The manifest revision changed; the response contains the authoritative current manifest state from the same snapshot as the returned ETag. */
        ManifestRevisionMismatch: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["ETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "revision_mismatch",
                 *         "message": "The project manifest changed. Review the current state before saving again.",
                 *         "request_id": "req_01JEXAMPLE",
                 *         "current_revision": 2,
                 *         "current_state": {
                 *           "project": {
                 *             "id": "photo-editor",
                 *             "name": "Photo Editor from Git",
                 *             "pack_ref": "mobile-ad-monetization/v1",
                 *             "source_type": "managed-file"
                 *           },
                 *           "environments": [
                 *             {
                 *               "id": "development",
                 *               "name": "Development",
                 *               "kind": "development",
                 *               "provider": {
                 *                 "type": "firebase-remote-config",
                 *                 "project_id": "photo-editor-dev"
                 *               },
                 *               "publish": {
                 *                 "requires_confirmation": false
                 *               }
                 *             }
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ManifestRevisionMismatchResponse"];
            };
        };
        /** @description Request is structurally valid but violates project rules. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested pack schema version is not compatible with this pack version. */
        SchemaIncompatible: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Mutation body is not application/json. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description If-Match is required for this mutation. */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        EnvironmentID: string;
        /** @description Quoted local manifest revision returned by ETag. */
        IfMatch: string;
        PackName: string;
        PackVersion: string;
        /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
        SchemaVersion: number;
    };
    requestBodies: never;
    headers: {
        CacheControl: "no-store";
        /** @description Quoted local manifest revision. */
        ETag: string;
        /** @description Quoted in-process Pack registry revision; this is independent of the project manifest revision. */
        PackETag: string;
        RequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The project manifest is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap context */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local manifest revision returned by ETag. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInput"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environments */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentsResponse"];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local manifest revision returned by ETag. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvironmentInput"];
            };
        };
        responses: {
            /** @description Created environment */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["StateConflict"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local manifest revision returned by ETag. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEnvironmentInput"];
            };
        };
        responses: {
            /** @description Updated environment */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local manifest revision returned by ETag. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted environment ID */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteEnvironmentResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["StateConflict"];
            412: components["responses"]["ManifestRevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered pack summaries */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackListResponse"];
                };
            };
        };
    };
    getPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pack metadata */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackMetadataResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPackSchema: {
        parameters: {
            query?: {
                /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
                schema_version?: components["parameters"]["SchemaVersion"];
            };
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned, declarative pack schema */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackSchemaResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["SchemaIncompatible"];
        };
    };
}
