/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health and the loaded project */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load the GUI bootstrap context */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active source adapter and its capabilities */
        get: operations["getSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active source digest and managed file status */
        get: operations["getSourceStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the loaded project */
        get: operations["getProject"];
        /** Replace editable project metadata */
        put: operations["updateProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project environments */
        get: operations["listEnvironments"];
        put?: never;
        /** Create an environment */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        /** Get an environment */
        get: operations["getEnvironment"];
        /** Replace an environment without changing its ID */
        put: operations["updateEnvironment"];
        post?: never;
        /** Delete an environment */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in configuration packs */
        get: operations["listPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/{pack_name}/versions/{pack_version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        /** Get a versioned configuration pack metadata */
        get: operations["getPack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/{pack_name}/versions/{pack_version}/schema": {
        parameters: {
            query?: {
                /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
                schema_version?: components["parameters"]["SchemaVersion"];
            };
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        /** Get a configuration pack form schema */
        get: operations["getPackSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        /** Get the targeted draft view for an environment */
        get: operations["getDraft"];
        /** Replace one targeted draft scope */
        put: operations["replaceDraftScope"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}:reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install an explicit empty object replacement in one draft scope */
        post: operations["resetDraftScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}:discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove one draft replacement and resolve the current source layer */
        post: operations["discardDraftScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}:save": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save the current visible draft replacements to the source */
        post: operations["saveDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        /** List effective Pack entities for an environment draft view */
        get: operations["listDraftEntities"];
        put?: never;
        /** Create one entity in a targeted draft scope */
        post: operations["createDraftEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}/entities/{entity_type}/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
                entity_type: components["parameters"]["EntityType"];
                entity_id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /** Get one effective Pack entity for an environment draft view */
        get: operations["getDraftEntity"];
        /** Replace one entity in a targeted draft scope */
        put: operations["replaceDraftEntity"];
        post?: never;
        /** Delete one entity from a targeted draft scope */
        delete: operations["deleteDraftEntity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}/entities/{entity_type}/{entity_id}/referenced-by": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
                entity_type: components["parameters"]["EntityType"];
                entity_id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /** List effective entities that reference one entity */
        get: operations["getDraftEntityReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}:validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run and store a complete validation result for the current draft snapshot */
        post: operations["validateDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        /** Get the most recent complete validation result for an environment */
        get: operations["getDraftDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            project_id: string;
        };
        BootstrapResponse: {
            data: components["schemas"]["BootstrapData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        BootstrapData: {
            project: components["schemas"]["Project"];
            environments: components["schemas"]["Environment"][];
            capabilities: components["schemas"]["Capabilities"];
        };
        SourceResponse: {
            data: components["schemas"]["Source"];
            meta: components["schemas"]["ResponseMeta"];
        };
        SourceStatusResponse: {
            data: components["schemas"]["SourceStatus"];
            meta: components["schemas"]["ResponseMeta"];
        };
        Source: {
            /** @enum {string} */
            type: "managed-file";
            capabilities: components["schemas"]["SourceCapabilities"];
        };
        SourceCapabilities: {
            load: boolean;
            save: boolean;
        };
        SourceStatus: {
            /** @enum {string} */
            type: "managed-file";
            /** @description Opaque digest derived from canonical source bytes. */
            digest: string;
            /** @description Whether the current digest differs from the last successful source load. */
            external_modified: boolean;
            /** @description Non-null workspace-relative managed file paths. No credentials are included. */
            paths: string[];
        };
        ManifestState: {
            project: components["schemas"]["Project"];
            environments: components["schemas"]["Environment"][];
        };
        ProjectResponse: {
            data: components["schemas"]["Project"];
            meta: components["schemas"]["ResponseMeta"];
        };
        EnvironmentsResponse: {
            data: components["schemas"]["Environment"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        EnvironmentResponse: {
            data: components["schemas"]["Environment"];
            meta: components["schemas"]["ResponseMeta"];
        };
        DeleteEnvironmentResponse: {
            data: {
                deleted_id: string;
            };
            meta: components["schemas"]["ResponseMeta"];
        };
        PackListResponse: {
            data: components["schemas"]["PackSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        PackMetadataResponse: {
            data: components["schemas"]["PackMetadata"];
            meta: components["schemas"]["ResponseMeta"];
        };
        PackSchemaResponse: {
            data: components["schemas"]["PackSchema"];
            meta: components["schemas"]["ResponseMeta"];
        };
        ResponseMeta: {
            request_id: string;
            revision: number;
        };
        Project: {
            id: string;
            name: string;
            pack_ref: string;
            /** @enum {string} */
            source_type: "managed-file" | "git-json";
        };
        UpdateProjectInput: {
            id: string;
            name: string;
        };
        /**
         * @example {
         *       "id": "production",
         *       "name": "Production",
         *       "kind": "production",
         *       "provider": {
         *         "type": "firebase-remote-config",
         *         "project_id": "photo-editor-prod"
         *       },
         *       "publish": {
         *         "requires_confirmation": true
         *       }
         *     }
         */
        Environment: {
            /** @description Stable opaque environment identifier. It cannot be changed after creation and carries no environment semantics. */
            id: string;
            /** @description Human-readable environment name shown in the UI. */
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        CreateEnvironmentInput: {
            id: string;
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        UpdateEnvironmentInput: {
            name: string;
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        /**
         * @description Server-authoritative environment category. Only production activates the persistent Production UI state. It cannot be changed after creation.
         * @enum {string}
         */
        EnvironmentKind: "development" | "staging" | "production" | "custom";
        ProviderConfig: {
            /** @constant */
            type: "firebase-remote-config";
            project_id: string;
        };
        PublishConfig: {
            requires_confirmation: boolean;
        };
        Capabilities: {
            /** @description Whether the current project source can be edited. Clients must render project forms as read-only when false. */
            project_edit: boolean;
            /** @description Whether environments can be created, updated, or deleted. Clients must render environment management as read-only when false. */
            environment_manage: boolean;
        };
        PackSummary: {
            ref: string;
            name: string;
            version: string;
            description: string;
        };
        PackMetadata: {
            ref: string;
            name: string;
            version: string;
            description: string;
            capabilities: string[];
            schema_version: number;
            entity_types: components["schemas"]["EntityMetadata"][];
        };
        EntityMetadata: {
            name: string;
            label: string;
            description: string;
            id_rule: components["schemas"]["IDRule"];
            /** @enum {string} */
            deletion_policy: "restrict" | "cascade" | "allow";
            environment_override_fields: string[];
        };
        IDRule: {
            pattern: string;
            min_length: number;
            max_length: number;
        };
        PackSchema: {
            version: number;
            entities: components["schemas"]["EntitySchema"][];
            migrations: components["schemas"]["SchemaMigration"][];
        };
        /** @description Pack-declared entity type. Clients treat it as opaque outside schema-driven display. */
        EntityType: string;
        /** @description Stable opaque entity reference in entity:{pack_ref}:{entity_type}:{entity_id} format. */
        EntityRef: string;
        EntityRecord: {
            /** @description Stable entity ID. It must match the entity_id path parameter for a replacement. */
            id: string;
            /** @description Complete Pack-declared entity field object. Concrete fields come from the Pack schema. */
            fields: {
                [key: string]: unknown;
            };
        };
        EntityPresence: components["schemas"]["MissingEntity"] | components["schemas"]["PresentEntity"];
        MissingEntity: {
            /** @constant */
            present: false;
        };
        PresentEntity: {
            /** @constant */
            present: true;
            value: components["schemas"]["EntityRecord"];
        };
        /**
         * @description Layer that supplies the entity effective value.
         * @enum {string}
         */
        EntityOrigin: "pack_default" | "baseline" | "draft_baseline" | "environment_override" | "draft_environment_override";
        EntityView: {
            entity_ref: components["schemas"]["EntityRef"];
            entity_type: components["schemas"]["EntityType"];
            entity_id: string;
            source: components["schemas"]["EntityPresence"];
            draft: components["schemas"]["EntityPresence"];
            resolved: components["schemas"]["EntityPresence"];
            effective: components["schemas"]["PresentEntity"];
            origin: components["schemas"]["EntityOrigin"];
            source_revision: string;
        };
        EntityReference: {
            entity_ref: components["schemas"]["EntityRef"];
            entity_type: components["schemas"]["EntityType"];
            entity_id: string;
            /** @description RFC 6901 JSON Pointer inside the referencing entity. */
            path: string;
        };
        EntitiesResponse: {
            /** @description Non-null entity views sorted by entity_type and entity_id. */
            data: components["schemas"]["EntityView"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        EntityResponse: {
            data: components["schemas"]["EntityView"];
            meta: components["schemas"]["ResponseMeta"];
        };
        EntityReferencesData: {
            entity_ref: components["schemas"]["EntityRef"];
            /** @description Non-null referenced_by entries sorted by entity_ref. */
            referenced_by: components["schemas"]["EntityReference"][];
        };
        EntityReferencesResponse: {
            data: components["schemas"]["EntityReferencesData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        CreateEntityInput: {
            expected_source_revision: string;
            write_scope: components["schemas"]["DraftWriteScope"];
            entity_type: components["schemas"]["EntityType"];
            entity: components["schemas"]["EntityRecord"];
        };
        EntityMutationInput: {
            expected_source_revision: string;
            write_scope: components["schemas"]["DraftWriteScope"];
            entity: components["schemas"]["EntityRecord"];
        };
        EntityDeleteInput: {
            expected_source_revision: string;
            write_scope: components["schemas"]["DraftWriteScope"];
        };
        EntitySchema: {
            name: string;
            fields: components["schemas"]["FieldSchema"][];
        };
        FieldSchema: {
            name: string;
            /** @enum {string} */
            type: "string" | "boolean" | "integer" | "number" | "object" | "array" | "reference";
            required: boolean;
            /** @description Whether an explicit JSON null is a valid configured value. This is independent of required. */
            nullable: boolean;
            default: unknown;
            /** @enum {string} */
            sensitivity: "public" | "sensitive";
            ui: components["schemas"]["FieldUI"];
            validation: components["schemas"]["FieldValidation"];
        };
        FieldUI: {
            label: string;
            description: string;
            control: string;
            group: string;
            order: number;
            placeholder?: string;
        };
        FieldValidation: {
            enum: unknown[];
            min_length?: number;
            max_length?: number;
            minimum?: number;
            maximum?: number;
        };
        SchemaMigration: {
            from_version: number;
            to_version: number;
            description: string;
        };
        DraftResponse: {
            data: components["schemas"]["DraftView"];
            meta: components["schemas"]["ResponseMeta"];
        };
        DraftView: {
            /** @description Environment view used to resolve environment_override. It does not make baseline environment-private. */
            environment_id: string;
            pack_ref: string;
            /** @description Opaque Source Adapter snapshot revision; never used as an HTTP ETag. */
            source_revision: string;
            /** @description Whether the shared baseline or this environment view has an installed replacement. Other environments are excluded. */
            dirty: boolean;
            /** @description Non-null scopes installed in this view (shared baseline and this environment only), sorted baseline before environment_override. Other environment overrides are excluded. */
            dirty_scopes: components["schemas"]["DraftWriteScope"][];
            baseline: components["schemas"]["DraftLayerState"];
            environment_override: components["schemas"]["DraftLayerState"];
            effective: components["schemas"]["Configuration"];
            /** @description Non-null field states sorted by RFC 6901 path. */
            field_states: components["schemas"]["FieldState"][];
            /** @description Non-null environments actually changed by the shared baseline and current-environment replacements represented in this view, holding other environment drafts constant, in project manifest order. */
            affected_environments: components["schemas"]["AffectedEnvironment"][];
        };
        /** @description A complete configuration object for one targeted layer. */
        Configuration: {
            [key: string]: unknown;
        };
        ConfigurationPresence: components["schemas"]["MissingConfiguration"] | components["schemas"]["PresentConfiguration"];
        MissingConfiguration: {
            /** @constant */
            present: false;
        };
        PresentConfiguration: {
            /** @constant */
            present: true;
            value: components["schemas"]["Configuration"];
        };
        DraftLayerState: {
            source: components["schemas"]["ConfigurationPresence"];
            draft: components["schemas"]["ConfigurationPresence"];
            resolved: components["schemas"]["ConfigurationPresence"];
            /** @description Whether a replacement is installed for this targeted layer. */
            dirty: boolean;
        };
        FieldValuePresence: components["schemas"]["MissingFieldValue"] | components["schemas"]["PresentFieldValue"];
        MissingFieldValue: {
            /** @constant */
            present: false;
        };
        PresentFieldValue: {
            /** @constant */
            present: true;
            /** @description Any JSON value, including null when the Pack field declares nullable true. */
            value: unknown;
        };
        FieldState: {
            /** @description RFC 6901 JSON Pointer. Tilde and slash tokens are escaped as ~0 and ~1. */
            path: string;
            pack_default: components["schemas"]["FieldValuePresence"];
            baseline: components["schemas"]["FieldValuePresence"];
            draft_baseline: components["schemas"]["FieldValuePresence"];
            environment_override: components["schemas"]["FieldValuePresence"];
            draft_environment_override: components["schemas"]["FieldValuePresence"];
            effective: components["schemas"]["FieldValuePresence"];
            origin: components["schemas"]["FieldOrigin"];
            environment_override_allowed: boolean;
            /** @description Whether the effective value comes from the source or draft environment override. */
            is_environment_overridden: boolean;
            /** @description Source snapshot used to produce every value in this field state. */
            source_revision: string;
            nullable: boolean;
        };
        /**
         * @description Effective value origin. Draft origins are distinct from source origins.
         * @enum {string}
         */
        FieldOrigin: "pack_default" | "baseline" | "draft_baseline" | "environment_override" | "draft_environment_override";
        AffectedEnvironment: {
            environment_id: string;
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
        };
        /** @enum {string} */
        DraftWriteScope: "baseline" | "environment_override";
        ReplaceDraftScopeInput: {
            expected_source_revision: string;
            write_scope: components["schemas"]["DraftWriteScope"];
            configuration: components["schemas"]["Configuration"];
        };
        DraftScopeMutationInput: {
            expected_source_revision: string;
            write_scope: components["schemas"]["DraftWriteScope"];
        };
        SaveDraftInput: {
            /** @description The source revision observed with the current draft. It is independent of If-Match. */
            expected_source_revision: string;
        };
        DraftRevisionMismatchResponse: {
            error: components["schemas"]["DraftRevisionMismatchError"] | components["schemas"]["SourceRevisionMismatchError"];
        };
        DraftSaveRevisionMismatchResponse: {
            error: components["schemas"]["DraftSaveRevisionMismatchError"] | components["schemas"]["DraftSaveSourceRevisionMismatchError"];
        };
        DraftSaveRevisionMismatchError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "revision_mismatch";
            message: string;
            request_id: string;
            current_revision: number;
            current_source_revision: string;
            /** @constant */
            conflict_scope: "source";
            current_state: components["schemas"]["DraftView"];
        };
        DraftSaveSourceRevisionMismatchError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "source_revision_mismatch";
            message: string;
            request_id: string;
            current_revision: number;
            current_source_revision: string;
            /** @constant */
            conflict_scope: "source";
            current_state: components["schemas"]["DraftView"];
        };
        DraftRevisionMismatchError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "revision_mismatch";
            message: string;
            request_id: string;
            current_revision: number;
            current_source_revision: string;
            /** @description Scope the failed request attempted to write; it does not identify the concurrent writer's changed scope. */
            conflict_scope: components["schemas"]["DraftWriteScope"];
            current_state: components["schemas"]["DraftView"];
        };
        SourceRevisionMismatchError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "source_revision_mismatch";
            message: string;
            request_id: string;
            current_revision: number;
            current_source_revision: string;
            /** @description Scope the failed request attempted to write; it does not identify the source change location. */
            conflict_scope: components["schemas"]["DraftWriteScope"];
            current_state: components["schemas"]["DraftView"];
        };
        DraftValidationErrorResponse: {
            error: components["schemas"]["DraftValidationError"];
        };
        DraftValidationError: {
            /** @constant */
            code: "validation_failed";
            message: string;
            request_id: string;
            /** @description Sorted by scope, RFC 6901 path, then code. */
            details: components["schemas"]["DraftStructuralErrorDetail"][];
        };
        DraftStructuralErrorDetail: {
            /** @enum {string} */
            code: "invalid_config_shape" | "field_type_mismatch" | "required_field_missing" | "value_not_allowed" | "explicit_null_forbidden" | "environment_override_forbidden";
            /** @description RFC 6901 JSON Pointer to the invalid configuration field. */
            path: string;
            /** @description Present when the structural field belongs to one identifiable Pack entity; omitted for Pack-neutral or root-level errors. */
            entity_ref?: components["schemas"]["EntityRef"];
            scope: components["schemas"]["DraftWriteScope"];
            message: string;
        };
        /**
         * @description Freshness of a stored result relative to the current project-level draft revision.
         * @enum {string}
         */
        ValidationStatus: "fresh" | "stale";
        /**
         * @description Complete-validation readiness before later Plan and Provider preconditions are applied.
         * @enum {string}
         */
        ValidationReadiness: "ready" | "blocked";
        /**
         * @description Closed severity enum. UI maps info to suggestion, warning to warning, and error or blocking to blocking.
         * @enum {string}
         */
        DiagnosticSeverity: "info" | "warning" | "error" | "blocking";
        Diagnostic: {
            code: string;
            /** @description RFC 6901 JSON Pointer to the invalid field or entity location. */
            path: string;
            severity: components["schemas"]["DiagnosticSeverity"];
            /** @description Human-readable message. Clients must not parse it for behavior. */
            message: string;
            entity_ref?: components["schemas"]["EntityRef"];
            fix_suggestion: string;
            /** Format: uri */
            documentation_url?: string;
        };
        ValidationResult: {
            environment_id: string;
            validated_draft_revision: number;
            /** Format: date-time */
            validated_at: string;
            status: components["schemas"]["ValidationStatus"];
            readiness: components["schemas"]["ValidationReadiness"];
            /** @description Non-null diagnostics sorted by severity rank, entity_ref, path, then code. */
            diagnostics: components["schemas"]["Diagnostic"][];
        };
        ValidationResponse: {
            data: components["schemas"]["ValidationResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        EntityReferencedErrorResponse: {
            error: components["schemas"]["EntityReferencedError"];
        };
        EntityReferencedError: {
            /** @constant */
            code: "entity_referenced";
            message: string;
            request_id: string;
            current_revision: number;
            /** @description Effective references sorted by entity_ref. */
            references: components["schemas"]["EntityReference"][];
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
        ManifestRevisionMismatchResponse: {
            error: components["schemas"]["ManifestRevisionMismatchError"];
        };
        ManifestRevisionMismatchError: {
            /** @constant */
            code: "revision_mismatch";
            message: string;
            request_id: string;
            /** @description Revision of current_state and the ETag response header. */
            current_revision: number;
            current_state: components["schemas"]["ManifestState"];
        };
        Error: {
            code: string;
            message: string;
            request_id: string;
            current_revision?: number;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            path?: string;
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description Malformed JSON, unknown fields, or invalid request headers. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Browser origin is not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists or the current state forbids the operation. */
        StateConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The manifest revision changed; the response contains the authoritative current manifest state from the same snapshot as the returned ETag. */
        ManifestRevisionMismatch: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["ETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "revision_mismatch",
                 *         "message": "The project manifest changed. Review the current state before saving again.",
                 *         "request_id": "req_01JEXAMPLE",
                 *         "current_revision": 2,
                 *         "current_state": {
                 *           "project": {
                 *             "id": "photo-editor",
                 *             "name": "Photo Editor from Git",
                 *             "pack_ref": "mobile-ad-monetization/v1",
                 *             "source_type": "managed-file"
                 *           },
                 *           "environments": [
                 *             {
                 *               "id": "development",
                 *               "name": "Development",
                 *               "kind": "development",
                 *               "provider": {
                 *                 "type": "firebase-remote-config",
                 *                 "project_id": "photo-editor-dev"
                 *               },
                 *               "publish": {
                 *                 "requires_confirmation": false
                 *               }
                 *             }
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ManifestRevisionMismatchResponse"];
            };
        };
        /** @description The targeted mutation was accepted, consumed the previous ETag, and the response contains the committed draft snapshot. Accepted no-op writes also advance the project-level draft revision. */
        DraftMutationSucceeded: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftResponse"];
            };
        };
        /** @description The project-level draft revision or source revision changed. The ETag and complete current state come from the same atomic snapshot. */
        DraftRevisionMismatch: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftRevisionMismatchResponse"];
            };
        };
        /** @description The project-level draft revision or source revision changed while saving to the source. The ETag and complete current state come from the same atomic snapshot. */
        DraftSaveRevisionMismatch: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftSaveRevisionMismatchResponse"];
            };
        };
        /** @description The replacement violates the Pack structural schema, nullability, or environment override permissions. */
        DraftValidationFailed: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftValidationErrorResponse"];
            };
        };
        /** @description The targeted entity was created and the project-level draft revision advanced. */
        EntityMutationCreated: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "data": {
                 *         "entity_ref": "entity:mobile-ad-monetization/v1:frequency_policy:launch_cap",
                 *         "entity_type": "frequency_policy",
                 *         "entity_id": "launch_cap",
                 *         "source": {
                 *           "present": false
                 *         },
                 *         "draft": {
                 *           "present": true,
                 *           "value": {
                 *             "id": "launch_cap",
                 *             "fields": {
                 *               "cooldown_ms": 30000
                 *             }
                 *           }
                 *         },
                 *         "resolved": {
                 *           "present": true,
                 *           "value": {
                 *             "id": "launch_cap",
                 *             "fields": {
                 *               "cooldown_ms": 30000
                 *             }
                 *           }
                 *         },
                 *         "effective": {
                 *           "present": true,
                 *           "value": {
                 *             "id": "launch_cap",
                 *             "fields": {
                 *               "cooldown_ms": 30000
                 *             }
                 *           }
                 *         },
                 *         "origin": "draft_baseline",
                 *         "source_revision": "src_01JEXAMPLE"
                 *       },
                 *       "meta": {
                 *         "request_id": "req_01JEXAMPLE",
                 *         "revision": 13
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["EntityResponse"];
            };
        };
        /** @description The targeted entity mutation was accepted and the project-level draft revision advanced. */
        EntityMutationSucceeded: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "data": {
                 *         "entity_ref": "entity:mobile-ad-monetization/v1:placement:ad_interstitial_001",
                 *         "entity_type": "placement",
                 *         "entity_id": "ad_interstitial_001",
                 *         "source": {
                 *           "present": true,
                 *           "value": {
                 *             "id": "ad_interstitial_001",
                 *             "fields": {
                 *               "frequency_policy_id": "inter_global_cap"
                 *             }
                 *           }
                 *         },
                 *         "draft": {
                 *           "present": true,
                 *           "value": {
                 *             "id": "ad_interstitial_001",
                 *             "fields": {
                 *               "frequency_policy_id": "app_open_session_gate"
                 *             }
                 *           }
                 *         },
                 *         "resolved": {
                 *           "present": true,
                 *           "value": {
                 *             "id": "ad_interstitial_001",
                 *             "fields": {
                 *               "frequency_policy_id": "app_open_session_gate"
                 *             }
                 *           }
                 *         },
                 *         "effective": {
                 *           "present": true,
                 *           "value": {
                 *             "id": "ad_interstitial_001",
                 *             "fields": {
                 *               "frequency_policy_id": "app_open_session_gate"
                 *             }
                 *           }
                 *         },
                 *         "origin": "draft_baseline",
                 *         "source_revision": "src_01JEXAMPLE"
                 *       },
                 *       "meta": {
                 *         "request_id": "req_01JEXAMPLE",
                 *         "revision": 14
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["EntityResponse"];
            };
        };
        /** @description A restrict-deletion entity still has effective references. The typed references list is non-empty and must be used instead of parsing the message. */
        EntityReferenced: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "entity_referenced",
                 *         "message": "The frequency policy is still referenced by 10 placements.",
                 *         "request_id": "req_01JEXAMPLE",
                 *         "current_revision": 12,
                 *         "references": [
                 *           {
                 *             "entity_ref": "entity:mobile-ad-monetization/v1:placement:ad_interstitial_001",
                 *             "entity_type": "placement",
                 *             "entity_id": "ad_interstitial_001",
                 *             "path": "/frequency_policy_id"
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["EntityReferencedErrorResponse"];
            };
        };
        /** @description Request is structurally valid but violates project rules. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested pack schema version is not compatible with this pack version. */
        SchemaIncompatible: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Mutation body is not application/json. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description If-Match is required for this mutation. */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        EnvironmentID: string;
        /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
        IfMatch: string;
        PackName: string;
        PackVersion: string;
        /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
        SchemaVersion: number;
        /** @description Optional Pack entity type filter. Omit to return every effective entity type. */
        EntityTypeQuery: components["schemas"]["EntityType"];
        EntityType: components["schemas"]["EntityType"];
        EntityID: string;
    };
    requestBodies: never;
    headers: {
        CacheControl: "no-store";
        /** @description Quoted local manifest revision. */
        ETag: string;
        /** @description Quoted project-level draft revision shared by baseline and every environment override. */
        DraftETag: string;
        /** @description Quoted in-process Pack registry revision; this is independent of the project manifest revision. */
        PackETag: string;
        RequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The project manifest is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap context */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active source adapter */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Source is temporarily unavailable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSourceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source status without credentials */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatusResponse"];
                };
            };
            /** @description Source is temporarily unavailable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInput"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environments */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentsResponse"];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvironmentInput"];
            };
        };
        responses: {
            /** @description Created environment */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["StateConflict"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEnvironmentInput"];
            };
        };
        responses: {
            /** @description Updated environment */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted environment ID */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteEnvironmentResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["StateConflict"];
            412: components["responses"]["ManifestRevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered pack summaries */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackListResponse"];
                };
            };
        };
    };
    getPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pack metadata */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackMetadataResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPackSchema: {
        parameters: {
            query?: {
                /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
                schema_version?: components["parameters"]["SchemaVersion"];
            };
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned, declarative pack schema */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackSchemaResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["SchemaIncompatible"];
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft layers, effective configuration, and field origins for the selected environment. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceDraftScope: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceDraftScopeInput"];
            };
        };
        responses: {
            200: components["responses"]["DraftMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["DraftValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    resetDraftScope: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftScopeMutationInput"];
            };
        };
        responses: {
            200: components["responses"]["DraftMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    discardDraftScope: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftScopeMutationInput"];
            };
        };
        responses: {
            200: components["responses"]["DraftMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    saveDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDraftInput"];
            };
        };
        responses: {
            /** @description Source was updated and the visible draft replacements were cleared */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftSaveRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listDraftEntities: {
        parameters: {
            query?: {
                /** @description Optional Pack entity type filter. Omit to return every effective entity type. */
                entity_type?: components["parameters"]["EntityTypeQuery"];
            };
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective entities and their source, draft, and resolved presence states */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitiesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createDraftEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityInput"];
            };
        };
        responses: {
            201: components["responses"]["EntityMutationCreated"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["DraftValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    getDraftEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
                entity_type: components["parameters"]["EntityType"];
                entity_id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity and its source, draft, and resolved presence states */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceDraftEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
                entity_type: components["parameters"]["EntityType"];
                entity_id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityMutationInput"];
            };
        };
        responses: {
            200: components["responses"]["EntityMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["DraftValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    deleteDraftEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
                entity_type: components["parameters"]["EntityType"];
                entity_id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityDeleteInput"];
            };
        };
        responses: {
            200: components["responses"]["EntityMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["EntityReferenced"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["DraftValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    getDraftEntityReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
                entity_type: components["parameters"]["EntityType"];
                entity_id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable referenced_by entries for the requested effective entity, sorted by entity_ref */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "entity_ref": "entity:mobile-ad-monetization/v1:frequency_policy:inter_global_cap",
                     *         "referenced_by": [
                     *           {
                     *             "entity_ref": "entity:mobile-ad-monetization/v1:placement:ad_interstitial_001",
                     *             "entity_type": "placement",
                     *             "entity_id": "ad_interstitial_001",
                     *             "path": "/frequency_policy_id"
                     *           }
                     *         ]
                     *       },
                     *       "meta": {
                     *         "request_id": "req_01JEXAMPLE",
                     *         "revision": 12
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["EntityReferencesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    validateDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete validation result bound to the captured project-level draft revision */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "environment_id": "production",
                     *         "validated_draft_revision": 12,
                     *         "validated_at": "2026-07-11T09:30:00Z",
                     *         "status": "fresh",
                     *         "readiness": "blocked",
                     *         "diagnostics": [
                     *           {
                     *             "code": "production_unit_binding_missing",
                     *             "path": "/unit_bindings/ub_production_ios_ad_native_006",
                     *             "severity": "warning",
                     *             "message": "Production is missing the iOS unit ID for native_document_scan_result_recommendation.",
                     *             "entity_ref": "entity:mobile-ad-monetization/v1:unit_binding:ub_production_ios_ad_native_006",
                     *             "fix_suggestion": "Configure a production iOS unit ID or disable the placement."
                     *           }
                     *         ]
                     *       },
                     *       "meta": {
                     *         "request_id": "req_01JEXAMPLE",
                     *         "revision": 12
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDraftDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent result; status is stale when the project-level draft revision has advanced */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description No complete validation result has been stored for this environment. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
