/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health and the loaded project */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load the GUI bootstrap context */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the loaded project */
        get: operations["getProject"];
        /** Replace editable project metadata */
        put: operations["updateProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project environments */
        get: operations["listEnvironments"];
        put?: never;
        /** Create an environment */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        /** Get an environment */
        get: operations["getEnvironment"];
        /** Replace an environment without changing its ID */
        put: operations["updateEnvironment"];
        post?: never;
        /** Delete an environment */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in configuration packs */
        get: operations["listPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/{pack_name}/versions/{pack_version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        /** Get a versioned configuration pack metadata */
        get: operations["getPack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/{pack_name}/versions/{pack_version}/schema": {
        parameters: {
            query?: {
                /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
                schema_version?: components["parameters"]["SchemaVersion"];
            };
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        /** Get a configuration pack form schema */
        get: operations["getPackSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        /** Get the targeted draft view for an environment */
        get: operations["getDraft"];
        /** Replace one targeted draft scope */
        put: operations["replaceDraftScope"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}:reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install an explicit empty object replacement in one draft scope */
        post: operations["resetDraftScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{environment_id}:discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove one draft replacement and resolve the current source layer */
        post: operations["discardDraftScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            project_id: string;
        };
        BootstrapResponse: {
            data: components["schemas"]["BootstrapData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        BootstrapData: {
            project: components["schemas"]["Project"];
            environments: components["schemas"]["Environment"][];
            capabilities: components["schemas"]["Capabilities"];
        };
        ManifestState: {
            project: components["schemas"]["Project"];
            environments: components["schemas"]["Environment"][];
        };
        ProjectResponse: {
            data: components["schemas"]["Project"];
            meta: components["schemas"]["ResponseMeta"];
        };
        EnvironmentsResponse: {
            data: components["schemas"]["Environment"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        EnvironmentResponse: {
            data: components["schemas"]["Environment"];
            meta: components["schemas"]["ResponseMeta"];
        };
        DeleteEnvironmentResponse: {
            data: {
                deleted_id: string;
            };
            meta: components["schemas"]["ResponseMeta"];
        };
        PackListResponse: {
            data: components["schemas"]["PackSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        PackMetadataResponse: {
            data: components["schemas"]["PackMetadata"];
            meta: components["schemas"]["ResponseMeta"];
        };
        PackSchemaResponse: {
            data: components["schemas"]["PackSchema"];
            meta: components["schemas"]["ResponseMeta"];
        };
        ResponseMeta: {
            request_id: string;
            revision: number;
        };
        Project: {
            id: string;
            name: string;
            pack_ref: string;
            /** @enum {string} */
            source_type: "managed-file" | "git-json";
        };
        UpdateProjectInput: {
            id: string;
            name: string;
        };
        /**
         * @example {
         *       "id": "production",
         *       "name": "Production",
         *       "kind": "production",
         *       "provider": {
         *         "type": "firebase-remote-config",
         *         "project_id": "photo-editor-prod"
         *       },
         *       "publish": {
         *         "requires_confirmation": true
         *       }
         *     }
         */
        Environment: {
            /** @description Stable opaque environment identifier. It cannot be changed after creation and carries no environment semantics. */
            id: string;
            /** @description Human-readable environment name shown in the UI. */
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        CreateEnvironmentInput: {
            id: string;
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        UpdateEnvironmentInput: {
            name: string;
            provider: components["schemas"]["ProviderConfig"];
            publish: components["schemas"]["PublishConfig"];
        };
        /**
         * @description Server-authoritative environment category. Only production activates the persistent Production UI state. It cannot be changed after creation.
         * @enum {string}
         */
        EnvironmentKind: "development" | "staging" | "production" | "custom";
        ProviderConfig: {
            /** @constant */
            type: "firebase-remote-config";
            project_id: string;
        };
        PublishConfig: {
            requires_confirmation: boolean;
        };
        Capabilities: {
            /** @description Whether the current project source can be edited. Clients must render project forms as read-only when false. */
            project_edit: boolean;
            /** @description Whether environments can be created, updated, or deleted. Clients must render environment management as read-only when false. */
            environment_manage: boolean;
        };
        PackSummary: {
            ref: string;
            name: string;
            version: string;
            description: string;
        };
        PackMetadata: {
            ref: string;
            name: string;
            version: string;
            description: string;
            capabilities: string[];
            schema_version: number;
            entity_types: components["schemas"]["EntityMetadata"][];
        };
        EntityMetadata: {
            name: string;
            label: string;
            description: string;
            id_rule: components["schemas"]["IDRule"];
            /** @enum {string} */
            deletion_policy: "restrict" | "cascade" | "allow";
            environment_override_fields: string[];
        };
        IDRule: {
            pattern: string;
            min_length: number;
            max_length: number;
        };
        PackSchema: {
            version: number;
            entities: components["schemas"]["EntitySchema"][];
            migrations: components["schemas"]["SchemaMigration"][];
        };
        EntitySchema: {
            name: string;
            fields: components["schemas"]["FieldSchema"][];
        };
        FieldSchema: {
            name: string;
            /** @enum {string} */
            type: "string" | "boolean" | "integer" | "number" | "object" | "array" | "reference";
            required: boolean;
            /** @description Whether an explicit JSON null is a valid configured value. This is independent of required. */
            nullable: boolean;
            default: unknown;
            /** @enum {string} */
            sensitivity: "public" | "sensitive";
            ui: components["schemas"]["FieldUI"];
            validation: components["schemas"]["FieldValidation"];
        };
        FieldUI: {
            label: string;
            description: string;
            control: string;
            group: string;
            order: number;
            placeholder?: string;
        };
        FieldValidation: {
            enum: unknown[];
            min_length?: number;
            max_length?: number;
            minimum?: number;
            maximum?: number;
        };
        SchemaMigration: {
            from_version: number;
            to_version: number;
            description: string;
        };
        DraftResponse: {
            data: components["schemas"]["DraftView"];
            meta: components["schemas"]["ResponseMeta"];
        };
        DraftView: {
            /** @description Environment view used to resolve environment_override. It does not make baseline environment-private. */
            environment_id: string;
            pack_ref: string;
            /** @description Opaque Source Adapter snapshot revision; never used as an HTTP ETag. */
            source_revision: string;
            /** @description Whether the shared baseline or this environment view has an installed replacement. Other environments are excluded. */
            dirty: boolean;
            /** @description Non-null scopes installed in this view (shared baseline and this environment only), sorted baseline before environment_override. Other environment overrides are excluded. */
            dirty_scopes: components["schemas"]["DraftWriteScope"][];
            baseline: components["schemas"]["DraftLayerState"];
            environment_override: components["schemas"]["DraftLayerState"];
            effective: components["schemas"]["Configuration"];
            /** @description Non-null field states sorted by RFC 6901 path. */
            field_states: components["schemas"]["FieldState"][];
            /** @description Non-null environments actually changed by the shared baseline and current-environment replacements represented in this view, holding other environment drafts constant, in project manifest order. */
            affected_environments: components["schemas"]["AffectedEnvironment"][];
        };
        /** @description A complete configuration object for one targeted layer. */
        Configuration: {
            [key: string]: unknown;
        };
        ConfigurationPresence: components["schemas"]["MissingConfiguration"] | components["schemas"]["PresentConfiguration"];
        MissingConfiguration: {
            /** @constant */
            present: false;
        };
        PresentConfiguration: {
            /** @constant */
            present: true;
            value: components["schemas"]["Configuration"];
        };
        DraftLayerState: {
            source: components["schemas"]["ConfigurationPresence"];
            draft: components["schemas"]["ConfigurationPresence"];
            resolved: components["schemas"]["ConfigurationPresence"];
            /** @description Whether a replacement is installed for this targeted layer. */
            dirty: boolean;
        };
        FieldValuePresence: components["schemas"]["MissingFieldValue"] | components["schemas"]["PresentFieldValue"];
        MissingFieldValue: {
            /** @constant */
            present: false;
        };
        PresentFieldValue: {
            /** @constant */
            present: true;
            /** @description Any JSON value, including null when the Pack field declares nullable true. */
            value: unknown;
        };
        FieldState: {
            /** @description RFC 6901 JSON Pointer. Tilde and slash tokens are escaped as ~0 and ~1. */
            path: string;
            pack_default: components["schemas"]["FieldValuePresence"];
            baseline: components["schemas"]["FieldValuePresence"];
            draft_baseline: components["schemas"]["FieldValuePresence"];
            environment_override: components["schemas"]["FieldValuePresence"];
            draft_environment_override: components["schemas"]["FieldValuePresence"];
            effective: components["schemas"]["FieldValuePresence"];
            origin: components["schemas"]["FieldOrigin"];
            environment_override_allowed: boolean;
            /** @description Whether the effective value comes from the source or draft environment override. */
            is_environment_overridden: boolean;
            /** @description Source snapshot used to produce every value in this field state. */
            source_revision: string;
            nullable: boolean;
        };
        /**
         * @description Effective value origin. Draft origins are distinct from source origins.
         * @enum {string}
         */
        FieldOrigin: "pack_default" | "baseline" | "draft_baseline" | "environment_override" | "draft_environment_override";
        AffectedEnvironment: {
            environment_id: string;
            name: string;
            kind: components["schemas"]["EnvironmentKind"];
        };
        /** @enum {string} */
        DraftWriteScope: "baseline" | "environment_override";
        ReplaceDraftScopeInput: {
            expected_source_revision: string;
            write_scope: components["schemas"]["DraftWriteScope"];
            configuration: components["schemas"]["Configuration"];
        };
        DraftScopeMutationInput: {
            expected_source_revision: string;
            write_scope: components["schemas"]["DraftWriteScope"];
        };
        DraftRevisionMismatchResponse: {
            error: components["schemas"]["DraftRevisionMismatchError"] | components["schemas"]["SourceRevisionMismatchError"];
        };
        DraftRevisionMismatchError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "revision_mismatch";
            message: string;
            request_id: string;
            current_revision: number;
            current_source_revision: string;
            /** @description Scope the failed request attempted to write; it does not identify the concurrent writer's changed scope. */
            conflict_scope: components["schemas"]["DraftWriteScope"];
            current_state: components["schemas"]["DraftView"];
        };
        SourceRevisionMismatchError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "source_revision_mismatch";
            message: string;
            request_id: string;
            current_revision: number;
            current_source_revision: string;
            /** @description Scope the failed request attempted to write; it does not identify the source change location. */
            conflict_scope: components["schemas"]["DraftWriteScope"];
            current_state: components["schemas"]["DraftView"];
        };
        DraftValidationErrorResponse: {
            error: components["schemas"]["DraftValidationError"];
        };
        DraftValidationError: {
            /** @constant */
            code: "validation_failed";
            message: string;
            request_id: string;
            /** @description Sorted by scope, RFC 6901 path, then code. */
            details: components["schemas"]["DraftStructuralErrorDetail"][];
        };
        DraftStructuralErrorDetail: {
            /** @enum {string} */
            code: "invalid_config_shape" | "field_type_mismatch" | "required_field_missing" | "value_not_allowed" | "explicit_null_forbidden" | "environment_override_forbidden";
            /** @description RFC 6901 JSON Pointer to the invalid configuration field. */
            path: string;
            scope: components["schemas"]["DraftWriteScope"];
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
        ManifestRevisionMismatchResponse: {
            error: components["schemas"]["ManifestRevisionMismatchError"];
        };
        ManifestRevisionMismatchError: {
            /** @constant */
            code: "revision_mismatch";
            message: string;
            request_id: string;
            /** @description Revision of current_state and the ETag response header. */
            current_revision: number;
            current_state: components["schemas"]["ManifestState"];
        };
        Error: {
            code: string;
            message: string;
            request_id: string;
            current_revision?: number;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            path?: string;
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description Malformed JSON, unknown fields, or invalid request headers. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Browser origin is not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists or the current state forbids the operation. */
        StateConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The manifest revision changed; the response contains the authoritative current manifest state from the same snapshot as the returned ETag. */
        ManifestRevisionMismatch: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["ETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "revision_mismatch",
                 *         "message": "The project manifest changed. Review the current state before saving again.",
                 *         "request_id": "req_01JEXAMPLE",
                 *         "current_revision": 2,
                 *         "current_state": {
                 *           "project": {
                 *             "id": "photo-editor",
                 *             "name": "Photo Editor from Git",
                 *             "pack_ref": "mobile-ad-monetization/v1",
                 *             "source_type": "managed-file"
                 *           },
                 *           "environments": [
                 *             {
                 *               "id": "development",
                 *               "name": "Development",
                 *               "kind": "development",
                 *               "provider": {
                 *                 "type": "firebase-remote-config",
                 *                 "project_id": "photo-editor-dev"
                 *               },
                 *               "publish": {
                 *                 "requires_confirmation": false
                 *               }
                 *             }
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ManifestRevisionMismatchResponse"];
            };
        };
        /** @description The targeted mutation was accepted, consumed the previous ETag, and the response contains the committed draft snapshot. Accepted no-op writes also advance the project-level draft revision. */
        DraftMutationSucceeded: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftResponse"];
            };
        };
        /** @description The project-level draft revision or source revision changed. The ETag and complete current state come from the same atomic snapshot. */
        DraftRevisionMismatch: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                ETag: components["headers"]["DraftETag"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftRevisionMismatchResponse"];
            };
        };
        /** @description The replacement violates the Pack structural schema, nullability, or environment override permissions. */
        DraftValidationFailed: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftValidationErrorResponse"];
            };
        };
        /** @description Request is structurally valid but violates project rules. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested pack schema version is not compatible with this pack version. */
        SchemaIncompatible: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Mutation body is not application/json. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description If-Match is required for this mutation. */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        EnvironmentID: string;
        /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
        IfMatch: string;
        PackName: string;
        PackVersion: string;
        /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
        SchemaVersion: number;
    };
    requestBodies: never;
    headers: {
        CacheControl: "no-store";
        /** @description Quoted local manifest revision. */
        ETag: string;
        /** @description Quoted project-level draft revision shared by baseline and every environment override. */
        DraftETag: string;
        /** @description Quoted in-process Pack registry revision; this is independent of the project manifest revision. */
        PackETag: string;
        RequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The project manifest is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap context */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInput"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environments */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentsResponse"];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvironmentInput"];
            };
        };
        responses: {
            /** @description Created environment */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["StateConflict"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEnvironmentInput"];
            };
        };
        responses: {
            /** @description Updated environment */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["ManifestRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted environment ID */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["ETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteEnvironmentResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["StateConflict"];
            412: components["responses"]["ManifestRevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered pack summaries */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackListResponse"];
                };
            };
        };
    };
    getPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pack metadata */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackMetadataResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPackSchema: {
        parameters: {
            query?: {
                /** @description Exact schema version understood by the client. Omit to retrieve the current schema. */
                schema_version?: components["parameters"]["SchemaVersion"];
            };
            header?: never;
            path: {
                pack_name: components["parameters"]["PackName"];
                pack_version: components["parameters"]["PackVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned, declarative pack schema */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["PackETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackSchemaResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["SchemaIncompatible"];
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft layers, effective configuration, and field origins for the selected environment. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceDraftScope: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceDraftScopeInput"];
            };
        };
        responses: {
            200: components["responses"]["DraftMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["DraftValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    resetDraftScope: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftScopeMutationInput"];
            };
        };
        responses: {
            200: components["responses"]["DraftMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    discardDraftScope: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted local resource revision returned by the same endpoint family. Manifest and draft revisions are distinct domains. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftScopeMutationInput"];
            };
        };
        responses: {
            200: components["responses"]["DraftMutationSucceeded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["DraftRevisionMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
}
